"""Durable records for dependency provisioning.

These records carry only facts the kernel's own tooling established. A
derivation says a committed lock was regenerated byte-identical from its
manifest under pinned resolution inputs, and names the package set that lock
selects for one target. An approval says a human accepted exactly that
package set. Neither says the dependencies are trustworthy — hashes prove
identity, approval mitigates hidden change, and ADR-007 records that the
approved code still executes inside the measured command.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class DepsDerivation:
    """One clean re-derivation of a committed lock, and what it selects."""

    lock_sha256: str
    depset_digest: str
    packages: Mapping[str, str]

    def as_record(self) -> dict[str, object]:
        """Return the exact, time-independent record stored in the journal."""

        return {
            "type": "deps-derivation",
            "lock_sha256": self.lock_sha256,
            "depset_digest": self.depset_digest,
            "packages": dict(self.packages),
        }


@dataclass(frozen=True, slots=True)
class DepsApproval:
    """A human's acceptance of one exact package set for one target."""

    depset_digest: str
    packages: Mapping[str, str]
    approver_id: str

    def as_record(self) -> dict[str, object]:
        """Return the approval record without a clock value."""

        return {
            "type": "deps-approval",
            "depset_digest": self.depset_digest,
            "packages": dict(self.packages),
            "approver_id": self.approver_id,
        }
