db-uri = "postgresql://authenticator:experiment-api@database:5432/postgres"
db-schemas = "api"
db-anon-role = "anon"
jwt-secret = "ranex-local-observer-public-test-secret-0123456789"
server-host = "0.0.0.0"
server-port = 3000
db-pool-acquisition-timeout = 1
