"""Public benchmark page for ranex, written for a NON-technical reader.

Every number is real and generated by code anyone can run — but it is always
presented next to a human-scale comparison (a camera flash, an eye-blink, a
heartbeat) and in everyday words. No kernel vocabulary anywhere on the page.

One self-contained HTML file: inline SVG charts, no external JS/CSS/fonts or
network calls. The fingerprint (sha256) of the raw data file is printed on
the page so the page and the data can be checked against each other.
"""

from __future__ import annotations

import hashlib
import html
import json
from pathlib import Path
from typing import Any

BG = "#0b1220"
CARD = "#111a2c"
INK = "#e6edf3"
MUTED = "#9aa8ba"
GOOD = "#4cc38a"
BAD = "#f0616d"
BLUE = "#58a6ff"
WARN = "#f0b429"

# Human time anchors used across the page (stated on the page itself).
# camera flash ≈ 1 ms · eye-blink ≈ 300 ms · heartbeat ≈ 1 s
def human_time(ms: float) -> str:
    if ms < 1:
        return "faster than a camera flash"
    if ms < 40:
        return "a tiny sliver of an eye-blink"
    if ms < 150:
        return "about a third of an eye-blink"
    if ms < 450:
        return "about one eye-blink"
    if ms < 1400:
        return "under one heartbeat"
    if ms < 3000:
        return "about one heartbeat"
    return "a couple of heartbeats"


# The cheat attempts we stage against ranex every night, in plain words.
# Each maps to a real, pinned scenario; a claim here the loop does not
# actually prove is a bug in this page.
CHEAT_ATTEMPTS = [
    ("The AI grades its own homework",
     "Blocked. The rule-checker refuses before it even looks at the work.", "verdict-self-approval-blocks"),
    ("Someone forges the seal on a report",
     "Rejected. A fake seal is spotted and named; it never counts as proof.", "admission-bad-signature"),
    ("Nobody ran the tests, but claims success",
     "Fails. Silence is not success — a check nobody ran fails the gate.", "verdict-absence-blocks"),
    ("Two reports disagree about the same test",
     "Fails. One pass cannot outvote one fail; disagreement itself blocks.", "verdict-contradiction-blocks"),
    ("We quietly edit an old record to hide a mistake",
     "Caught. The record book is chained: one edit is detected instantly.", "journal-tamper-detected"),
    ("We damage one page to see if the rest notice",
     "Caught. Every page after a damaged one visibly breaks — proven by "
     "recomputing the whole chain with plain math, not by trusting ranex.", "proof-journal-tamper-propagation"),
]

# Timed workloads shown on the page, with plain-language labels.
PLAIN_TIMINGS = [
    ("admission-200", "Check that 200 sealed reports are genuine"),
    ("verify-200", "Check 200 seals, one by one"),
    ("journal-append-2000", "Write 2,000 decisions into the record book"),
    ("journal-verify-2000", "Re-read a 2,000-page record book from scratch"),
    ("evaluate-20claims-100calls", "Decide 'is this work done?' 100 times"),
    ("cli-cold-start", "Start the ranex tool from cold"),
]


def _fmt(value: float) -> str:
    return f"{value:,.1f}" if value >= 10 else f"{value:,.2f}"


def bar_chart(rows: list[dict[str, Any]], title: str, note: str) -> str:
    """Horizontal bars. The big label is the human comparison; the exact
    measurement is the small print under it."""
    if not rows:
        return ""
    max_median = max(r["median"] for r in rows) or 1.0
    row_h, gap, top = 46, 18, 46
    label_w, value_w = 400, 210
    bar_max = 760 - label_w - value_w
    height = top + len(rows) * (row_h + gap) + 30
    parts = [
        '<svg viewBox="0 0 760 {}" xmlns="http://www.w3.org/2000/svg" '
        'font-family="ui-sans-serif,system-ui,sans-serif" role="img" '
        'aria-label="{}">'.format(height, html.escape(title)),
        '<text x="0" y="22" fill="{}" font-size="17" font-weight="600">{}</text>'
        .format(INK, html.escape(title)),
    ]
    for index, row in enumerate(rows):
        y = top + index * (row_h + gap)
        color = row.get("color", GOOD)
        bar_w = max(2.0, (row["median"] / max_median) * bar_max)
        x0 = label_w
        wx0 = x0 + (row["min"] / max_median) * bar_max
        wx1 = x0 + (row["max"] / max_median) * bar_max
        parts.append('<text x="0" y="{}" fill="{}" font-size="14">{}</text>'
                     .format(y + 18, INK, html.escape(row["label"][:56])))
        parts.append('<text x="0" y="{}" fill="{}" font-size="12">{}</text>'
                     .format(y + 34, MUTED, html.escape(row["human"])))
        parts.append('<line x1="{:.1f}" y1="{:.1f}" x2="{:.1f}" y2="{:.1f}" '
                     'stroke="{}" stroke-opacity="0.55" stroke-width="10"/>'
                     .format(wx0, y + row_h / 2, wx1, y + row_h / 2, color))
        parts.append('<rect x="{}" y="{}" width="{:.1f}" height="{}" rx="6" '
                     'fill="{}" fill-opacity="0.92"/>'
                     .format(x0, y, bar_w, row_h, color))
        parts.append('<text x="{:.1f}" y="{}" fill="{}" font-size="14" '
                     'font-weight="600">{} ms</text>'
                     .format(x0 + bar_w + 10, y + 28, INK, _fmt(row["median"])))
    parts.append('<text x="0" y="{}" fill="{}" font-size="12">{}</text>'
                 .format(height - 8, MUTED, html.escape(note)))
    parts.append("</svg>")
    return "".join(parts)


def line_chart(points: list[dict[str, Any]], title: str, subtitle: str,
               x_key: str, y_key: str, x_label: str, y_label: str,
               color: str, verdict: str) -> str:
    if len(points) < 2:
        return ""
    width, height, pad_l, pad_b, pad_t = 600, 310, 70, 46, 44
    plot_w, plot_h = width - pad_l - 20, height - pad_b - pad_t - 28
    xs = [p[x_key] for p in points]
    ys = [p[y_key] for p in points]
    xmin, xmax, ymin, ymax = min(xs), max(xs), min(ys), max(ys)
    if xmin == xmax:
        xmax = xmin + 1
    if ymin == ymax:
        ymax = ymin * 1.1 or 1

    def px(x: float) -> float:
        return pad_l + (x - xmin) / (xmax - xmin) * plot_w

    def py(y: float) -> float:
        return pad_t + plot_h - (y - ymin) / (ymax - ymin) * plot_h

    parts = [
        '<svg viewBox="0 0 {} {}" xmlns="http://www.w3.org/2000/svg" '
        'font-family="ui-sans-serif,system-ui,sans-serif" role="img" '
        'aria-label="{}">'.format(width, height, html.escape(title)),
        '<text x="0" y="22" fill="{}" font-size="17" font-weight="600">{}</text>'
        .format(INK, html.escape(title)),
        '<text x="0" y="40" fill="{}" font-size="13">{}</text>'
        .format(MUTED, html.escape(subtitle)),
        '<rect x="{}" y="{}" width="{}" height="{}" fill="none" stroke="{}" '
        'stroke-opacity="0.4"/>'.format(pad_l, pad_t, plot_w, plot_h, MUTED),
    ]
    for i in range(5):
        value = ymin + (ymax - ymin) * i / 4
        yy = py(value)
        parts.append('<line x1="{}" y1="{:.1f}" x2="{}" y2="{:.1f}" stroke="{}" '
                     'stroke-opacity="0.15"/>'.format(pad_l, yy, pad_l + plot_w, yy, MUTED))
        parts.append('<text x="{}" y="{:.1f}" fill="{}" font-size="12" '
                     'text-anchor="end">{}</text>'.format(pad_l - 8, yy + 5, MUTED, _fmt(value)))
    for point in points:
        parts.append('<text x="{:.1f}" y="{}" fill="{}" font-size="12" '
                     'text-anchor="middle">{:,}</text>'
                     .format(px(point[x_key]), pad_t + plot_h + 20, MUTED, point[x_key]))
    path = " ".join("{:.1f},{:.1f}".format(px(p[x_key]), py(p[y_key])) for p in points)
    parts.append('<polyline points="{}" fill="none" stroke="{}" stroke-width="3"/>'
                 .format(path, color))
    for point in points:
        parts.append('<circle cx="{:.1f}" cy="{:.1f}" r="5" fill="{}"/>'
                     .format(px(point[x_key]), py(point[y_key]), color))
    parts.append('<text x="{:.0f}" y="{}" fill="{}" font-size="12" text-anchor="middle">{}</text>'
                 .format(pad_l + plot_w / 2, pad_t + plot_h + 40, MUTED, html.escape(x_label)))
    parts.append('<text x="14" y="{:.0f}" fill="{}" font-size="12" text-anchor="middle" '
                 'transform="rotate(-90 14 {:.0f})">{}</text>'
                 .format(pad_t + plot_h / 2, MUTED, pad_t + plot_h / 2, html.escape(y_label)))
    parts.append('<text x="{}" y="{}" fill="{}" font-size="13" font-weight="600">{}</text>'
                 .format(pad_l, height - 4, color, html.escape(verdict)))
    parts.append("</svg>")
    return "".join(parts)


def _card(value: str, label: str, sub: str, color: str = INK) -> str:
    return ('<div class="card"><div class="value" style="color:{}">{}</div>'
            '<div class="label">{}</div><div class="sub">{}</div></div>'
            .format(color, html.escape(value), html.escape(label), html.escape(sub)))


def _area_of(scenario_id: str) -> str:
    try:
        from scenarios import SCENARIOS
    except ImportError:
        return ""
    return SCENARIOS.get(scenario_id, ("",))[0]


def generate_site(report: dict[str, Any], output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "benchmarks.json"
    json_payload = json.dumps(report, indent=2, sort_keys=True) + "\n"
    json_path.write_text(json_payload)
    digest = "sha256:" + hashlib.sha256(json_payload.encode("utf-8")).hexdigest()

    board = report["proof_board"]
    timings = {m["id"]: m for m in report["timings"]}
    env = report["environment"]

    idea_cards = "".join([
        _card("Sealed", "Proof, not promises",
              "Every piece of work arrives with an unforgeable seal, like a notary stamping a document.", GOOD),
        _card("Unbribable", "Rules decide, not opinions",
              "A fixed checklist decides when work counts as done. The AI cannot talk its way past it.", BLUE),
        _card("In pen", "The record book can't be quietly changed",
              "Every decision is written in ink and chained to the one before. Editing history leaves visible damage.", WARN),
    ])

    cheat_rows = []
    for title, outcome, scenario_id in CHEAT_ATTEMPTS:
        cheat_rows.append(
            '<div class="cheat"><div class="attempt"><span class="x">✗</span>{}'
            '</div><div class="result"><span class="check">✓</span>{}</div></div>'
            .format(html.escape(title), html.escape(outcome))
        )
    cheat_list = "".join(cheat_rows)

    bar_rows = []
    for metric_id, label in PLAIN_TIMINGS:
        if metric_id not in timings:
            continue
        metric = timings[metric_id]
        bar_rows.append({
            "label": label,
            "human": human_time(metric["median"]) + " (fastest run {}, slowest {} ms)"
                     .format(int(metric["min"]), int(metric["max"])),
            "median": metric["median"],
            "min": metric["min"], "max": metric["max"],
        })
    cost_chart = bar_chart(
        bar_rows,
        "How long the checking takes",
        "ms means thousandths of a second - a camera flash is about 1 ms, an eye-blink about 300 ms. "
        "Solid bar: typical time. Shaded band: fastest to slowest of 3 runs.")

    scaling = report.get("scaling", {})
    verify_points = scaling.get("journal-verify", [])
    append_points = [
        {"rows": p["rows"], "per_row_ms": p["median_ms"] / p["rows"]}
        for p in scaling.get("journal-append", [])
    ]
    scaling_charts = ""
    if len(verify_points) >= 2:
        growth = verify_points[-1]["median_ms"] / verify_points[0]["median_ms"]
        factor = verify_points[-1]["rows"] // verify_points[0]["rows"]
        verdict = "{}x the pages, {}x the reading time - a straight, predictable line".format(
            factor, round(growth))
        svg = line_chart(
            verify_points, "Re-reading the whole record book",
            "time to re-check every page of a book with N decisions",
            "rows", "median_ms", "pages in the record book", "thousandths of a second",
            GOOD, verdict)
        scaling_charts += '<div class="chart">' + svg + "</div>"
    if append_points:
        first = append_points[0]["per_row_ms"]
        ratio = (append_points[-1]["per_row_ms"] / first) if first else 1
        flat = abs(ratio - 1) < 0.5
        verdict = ("Flat line, as designed: old pages are never rewritten - "
                   "we also prove this letter by letter, not just by the clock"
                   if flat else "measurement only - the letter-by-letter proof is separate")
        svg = line_chart(
            append_points, "Writing one new page, as the book grows",
            "cost of adding one decision to a book that already holds N",
            "rows", "per_row_ms", "pages already written", "thousandths of a second",
            BLUE, verdict)
        scaling_charts += '<div class="chart">' + svg + "</div>"

    open_findings = board.get("findings_open", [])
    findings_note = (
        "Right now there is <strong>1 known imperfection</strong> we found in ourselves and "
        "published (in one rare kind of damage, the checker raises a loud alarm instead of "
        "writing its usual tidy report - it still never accepts damaged records; we are "
        "polishing that rough edge)."
        if open_findings else
        "Right now there are <strong>no known imperfections</strong> open."
    )

    page = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ranex — proof your AI helpers actually did the work</title>
<style>
  :root { color-scheme: dark; }
  body { margin:0; BACKGROUND; color: TEXT; font:17px/1.65 ui-sans-serif,system-ui,sans-serif; }
  main { max-width:760px; margin:0 auto; padding:48px 22px 100px; }
  h1 { font-size:31px; line-height:1.25; margin:0 0 12px; }
  h2 { font-size:23px; margin:56px 0 8px; }
  .lede { color: MUTED; font-size:18px; margin:0 0 32px; }
  .note { color: MUTED; margin:0 0 18px; }
  .cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(230px,1fr)); gap:14px; }
  .card { background: CARD; border:1px solid #1f2a3d; border-radius:14px; padding:20px; }
  .card .value { font-size:16px; font-weight:800; }
  .card .label { font-size:15px; font-weight:600; margin-top:8px; }
  .card .sub { color: MUTED; font-size:13.5px; margin-top:6px; }
  .cheat { background: CARD; border:1px solid #1f2a3d; border-radius:14px;
           padding:16px 20px; margin-bottom:12px; }
  .attempt { font-weight:600; font-size:15.5px; }
  .result { color: TEXT; font-size:14.5px; margin-top:6px; padding-left:2px; }
  .x { color: BAD; font-weight:800; margin-right:10px; }
  .check { color: GOOD; font-weight:800; margin-right:10px; }
  .chip { display:inline-block; margin-left:10px; padding:1px 10px; border:1px solid #2a3a55;
          border-radius:999px; color: MUTED; font-size:11px; font-weight:400; vertical-align:2px; }
  .chart { background: CARD; border:1px solid #1f2a3d; border-radius:14px; padding:22px;
           margin:16px 0; overflow-x:auto; }
  code { background: CARD; border:1px solid #1f2a3d; border-radius:6px; padding:2px 8px;
         font-size:14px; }
  footer { margin-top:60px; border-top:1px solid #1f2a3d; padding-top:22px;
           color: MUTED; font-size:13.5px; }
</style></head><body><main>
<h1>You ask an AI to build something. It says “done, all tests passed.”<br>Did they?</h1>
<p class="lede">ranex makes AI helpers <strong>hand over proof</strong> — like a receipt anyone
can check is genuine. This page shows that system working, in numbers anyone can re-create.</p>

<div class="cards">IDEA_CARDS</div>

<h2>Does it actually work? We try to cheat it every night.</h2>
<p class="note">CHEAT_COUNT of CHEAT_TOTAL cheat attempts are caught — every night, and each check
runs twice: if the two runs disagree by even a sliver, it counts as broken.</p>
<div class="cheats">CHEAT_LIST</div>

<h2>Is all that checking slow?</h2>
<p class="note">No — it is nearly free. Measured on one ordinary computer
(Python ENV_PY, ENV_CPU processors, ENV_SYS). Visitors with the software can re-run every number
with one command.</p>
<div class="chart">COST_CHART</div>

<h2>As the work piles up, does checking get slow?</h2>
<p class="note">Two things must stay true. Re-reading the record book should grow in a straight,
predictable line. And writing a new page must never slow down or disturb old pages.</p>
SCALING_CHARTS

<h2>Do we hide our own flaws?</h2>
<p class="note">No. FINDINGS_NOTE</p>
<p class="note">This whole page was drawn by a computer program from the project's own files —
nobody typed these numbers by hand. Anyone can regenerate it:</p>
<p><code>uv run --frozen python tools/dogfood/dogfood.py report</code></p>
<p class="note">And check the page against its data with this fingerprint:
<code>DIGEST</code></p>

<footer>ranex — proof-of-work for AI agents that build software ·
times describe one labeled computer and are shown with their measurement range ·
everything deterministic is checked twice, nightly</footer>
</main></body></html>
"""
    css = page
    css = css.replace("IDEA_CARDS", idea_cards)
    css = css.replace("CHEAT_COUNT", str(len(CHEAT_ATTEMPTS)))
    css = css.replace("CHEAT_TOTAL", str(len(CHEAT_ATTEMPTS)))
    css = css.replace("CHEAT_LIST", cheat_list)
    css = css.replace("ENV_PY", html.escape(env["python"]))
    css = css.replace("ENV_CPU", html.escape(env["cpu_count"]))
    css = css.replace("ENV_SYS", html.escape(env["system"]))
    css = css.replace("COST_CHART", cost_chart)
    css = css.replace("SCALING_CHARTS", scaling_charts)
    css = css.replace("FINDINGS_NOTE", findings_note)
    css = css.replace("DIGEST", digest)
    css = css.replace("BACKGROUND", "background:{};".format(BG))
    css = css.replace("TEXT;", "{};".format(INK)).replace("TEXT", INK)
    css = css.replace("MUTED", MUTED)
    css = css.replace("CARD", CARD)

    html_path = output_dir / "benchmark.html"
    html_path.write_text(css)
    return [html_path, json_path]
